export {AksyDistrict} from './aksy-district'
export {AlaBukaDistrict} from './ala-buka-district'
export {ChatkalDistrict} from './chatkal-district'
export {NookenDistrict} from './nooken-district'
export {SuzakDistrict} from './suzak-district'
export {BazarKorgonDistrict} from './bazar-korgon-district'
export {TogusToroDistrict} from './togus-toro-district'
export {ToktogulDistrict} from './toktogul-district'
