export const breakfastData = [
    {
        id: 101,
        name: 'Континентальный завтрак',
        nameEn: 'Continental Breakfast',
        description: 'Легкий европейский завтрак: круассан, сырная тарелка, киш Лорен, свежий сок и ароматный капучино',
        ingredients: ['Круассан', 'Бри', 'Камамбер', 'Козий сыр', 'Киш Лорен', 'Апельсин', 'Малиновый джем', 'Мёд', 'Сливочное масло', 'Багет', 'Капучино'],
        price: 500,
        oldPrice: 800,
        rating: 4.9,
        ratingCount: 156,
        image: 'https://kuran.kg/breakfast/101.webp',
        category: 'breakfast',
        tags: ['Хит', 'Континентальный', 'Европейский'],
        calories: 890,
        cookingTime: 15,
        isPopular: true,
        isVegetarian: true
    },
    {
        id: 102,
        name: 'Свежевыжатый апельсиновый сок',
        nameEn: 'Fresh Orange Juice',
        description: 'Витаминный заряд на весь день из спелых апельсинов',
        ingredients: ['Апельсины'],
        price: 390,
        rating: 4.8,
        ratingCount: 234,
        image: 'https://kuran.kg/breakfast/102.webp',
        category: 'breakfast',
        tags: ['Натуральное', 'Сок'],
        calories: 120,
        cookingTime: 3,
        isVegetarian: true,
        isGlutenFree: true
    },
    {
        id: 103,
        name: 'Натуральный греческий йогурт',
        nameEn: 'Greek Yogurt',
        description: 'Густой сливочный йогурт с живыми бифидобактериями',
        ingredients: ['Пастеризованное молоко', 'Закваска'],
        price: 250,
        rating: 4.7,
        ratingCount: 98,
        image: 'https://kuran.kg/breakfast/103.avif',
        category: 'breakfast',
        tags: ['Кисломолочное', 'ЗОЖ'],
        calories: 150,
        cookingTime: 2,
        isVegetarian: true,
        isGlutenFree: true
    },
    {
        id: 104,
        name: 'Круассан с маслом и джемом',
        nameEn: 'Croissant with Butter and Jam',
        description: 'Слоеный круассан с нежным сливочным маслом и домашним малиновым джемом',
        ingredients: ['Мука', 'Сливочное масло', 'Дрожжи', 'Сахар', 'Малиновый джем'],
        price: 340,
        rating: 4.9,
        ratingCount: 187,
        image: 'https://kuran.kg/breakfast/104.jpg',
        category: 'breakfast',
        tags: ['Выпечка', 'Популярное'],
        calories: 380,
        cookingTime: 5,
        isVegetarian: true,
        isPopular: true
    },
    {
        id: 105,
        name: 'Капучино с корицей',
        nameEn: 'Cinnamon Cappuccino',
        description: 'Классический итальянский кофе с нежной молочной пенкой и щепоткой корицы',
        ingredients: ['Эспрессо', 'Молоко', 'Корица'],
        price: 280,
        rating: 4.9,
        ratingCount: 312,
        image: 'https://kuran.kg/breakfast/105.webp',
        category: 'breakfast',
        tags: ['Кофе', 'Горячий напиток'],
        calories: 90,
        cookingTime: 4,
        isVegetarian: true
    },
    {
        id: 201,
        name: 'Расширенный завтрак',
        nameEn: 'Extended Breakfast',
        description: 'Сытный завтрак с мясной тарелкой, омлетом, панкейками, йогуртом с мюсли и свежевыжатым соком',
        ingredients: ['Ветчина', 'Прошутто', 'Салями', 'Брезаола', 'Омлет с грибами', 'Панкейки', 'Йогурт с мюсли', 'Апельсиновый сок', 'Зерновой тост', 'Латте', 'Джем сет'],
        price: 650,
        oldPrice: 800,
        rating: 4.8,
        ratingCount: 98,
        image: 'breakfast/201.jpg',
        category: 'breakfast',
        tags: ['Хит', 'Расширенный', 'Сытный'],
        calories: 1250,
        cookingTime: 25,
        isPopular: true
    },
    {
        id: 202,
        name: 'Свежевыжатый грейпфрутовый сок',
        nameEn: 'Fresh Grapefruit Juice',
        description: 'Бодрящий сок с горчинкой для идеального начала дня',
        ingredients: ['Грейпфрут'],
        price: 350,
        rating: 4.7,
        ratingCount: 78,
        image: 'https://kuran.kg/breakfast/202.jpg',
        category: 'breakfast',
        tags: ['Сок', 'Натуральное'],
        calories: 100,
        cookingTime: 3,
        isVegetarian: true,
        isGlutenFree: true
    },
    {
        id: 203,
        name: 'Мясная тарелка "Завтрак мясника"',
        nameEn: "Butcher's Breakfast Platter",
        description: 'Изысканная нарезка из итальянской ветчины, прошутто, салями и брезаолы',
        ingredients: ['Ветчина', 'Прошутто', 'Салями', 'Брезаола'],
        price: 590,
        rating: 4.9,
        ratingCount: 112,
        image: 'https://kuran.kg/breakfast/203.jpeg',
        category: 'breakfast',
        tags: ['Мясное', 'Холодная закуска'],
        calories: 320,
        cookingTime: 7,
        isPopular: true
    },
    {
        id: 204,
        name: 'Омлет с шампиньонами и моцареллой',
        nameEn: 'Omelette with Mushrooms and Mozzarella',
        description: 'Пышный омлет из трех яиц с лесными шампиньонами и тягучей моцареллой',
        ingredients: ['Яйца', 'Шампиньоны', 'Моцарелла', 'Сливки', 'Сливочное масло'],
        price: 420,
        rating: 4.8,
        ratingCount: 203,
        image: 'https://kuran.kg/breakfast/204.jpg',
        category: 'breakfast',
        tags: ['Горячее блюдо', 'Яйца'],
        calories: 380,
        cookingTime: 12,
        isVegetarian: true
    },
    {
        id: 205,
        name: 'Йогурт с мюсли и свежими ягодами',
        nameEn: 'Yogurt with Muesli and Fresh Berries',
        description: 'Домашний йогурт, хрустящие мюсли и голубика с малиной',
        ingredients: ['Натуральный йогурт', 'Мюсли', 'Голубика', 'Малина', 'Мёд'],
        price: 380,
        rating: 4.8,
        ratingCount: 145,
        image: 'https://kuran.kg/breakfast/205.jpg',
        category: 'breakfast',
        tags: ['Кисломолочное', 'ЗОЖ'],
        calories: 280,
        cookingTime: 5,
        isVegetarian: true,
        isPopular: true
    },
    {
        id: 206,
        name: 'Панкейки с кленовым сиропом',
        nameEn: 'Pancakes with Maple Syrup',
        description: 'Три воздушных американских панкейка, сливочное масло и натуральный кленовый сироп',
        ingredients: ['Мука', 'Яйца', 'Молоко', 'Сливочное масло', 'Кленовый сироп'],
        price: 350,
        rating: 4.9,
        ratingCount: 267,
        image: 'https://kuran.kg/breakfast/206.webp',
        category: 'breakfast',
        tags: ['Выпечка', 'Десерт', 'Популярное'],
        calories: 420,
        cookingTime: 12,
        isVegetarian: true,
        isPopular: true
    },
    {
        id: 207,
        name: 'Латте с ванильным сиропом',
        nameEn: 'Vanilla Latte',
        description: 'Нежный кофейный напиток с большим количеством горячего молока и ванилью',
        ingredients: ['Эспрессо', 'Молоко', 'Ванильный сироп'],
        price: 290,
        rating: 4.8,
        ratingCount: 198,
        image: 'https://kuran.kg/breakfast/207.JPG',
        category: 'breakfast',
        tags: ['Кофе', 'Горячий напиток'],
        calories: 120,
        cookingTime: 4,
        isVegetarian: true
    },
    {
        id: 301,
        name: 'Английский завтрак',
        nameEn: 'Full English Breakfast',
        description: 'Классика Туманного Альбиона: яичница-глазунья, бекон, сосиски, бобы, томаты, грибы, тост с маслом и апельсиновый мармелад',
        ingredients: ['Яйца', 'Бекон', 'Сосиски', 'Бобы в томате', 'Томаты черри', 'Шампиньоны', 'Тост', 'Сливочное масло', 'Апельсиновый мармелад'],
        price: 350,
        oldPrice: 750,
        rating: 4.9,
        ratingCount: 234,
        image: 'https://kuran.kg/breakfast/301.jpeg',
        category: 'breakfast',
        tags: ['Хит', 'Английский', 'Сытный'],
        calories: 980,
        cookingTime: 25,
        isPopular: true
    },
    {
        id: 302,
        name: 'Английский завтрак Twinings',
        nameEn: 'Twinings English Breakfast Tea',
        description: 'Крепкий черный чай с молоком — традиционное начало английского утра',
        ingredients: ['Черный чай', 'Молоко', 'Сахар'],
        price: 250,
        rating: 4.8,
        ratingCount: 189,
        image: 'https://kuran.kg/breakfast/302.jpg',
        category: 'breakfast',
        tags: ['Чай', 'Горячий напиток', 'Английский'],
        calories: 30,
        cookingTime: 3,
        isVegetarian: true
    },
    {
        id: 303,
        name: 'Рыбная тарелка "Fisherman’s Morning"',
        nameEn: "Fisherman's Morning Platter",
        description: 'Слабосоленый лосось, скумбрия холодного копчения и нежный рыбный паштет',
        ingredients: ['Лосось слабосоленый', 'Скумбрия холодного копчения', 'Рыбный паштет', 'Лимон', 'Каперсы'],
        price: 650,
        rating: 4.9,
        ratingCount: 67,
        image: 'https://kuran.kg/breakfast/303.avif',
        category: 'breakfast',
        tags: ['Рыба', 'Холодная закуска', 'Премиум'],
        calories: 340,
        cookingTime: 8,
        isPopular: true
    },
    {
        id: 304,
        name: 'Овсяная каша "Royal" с виски',
        nameEn: 'Royal Oatmeal with Whisky',
        description: 'Нежная овсяная каша на сливках с коричневым сахаром и каплей шотландского виски',
        ingredients: ['Овсяные хлопья', 'Сливки', 'Коричневый сахар', 'Виски', 'Ягоды'],
        price: 390,
        rating: 4.8,
        ratingCount: 89,
        image: 'https://kuran.kg/breakfast/304.jpg',
        category: 'breakfast',
        tags: ['Каша', 'Английский', 'Алкоголь'],
        calories: 350,
        cookingTime: 10,
        isVegetarian: true
    },
    {
        id: 305,
        name: 'Скир с мёдом',
        nameEn: 'Skyr with Honey',
        description: 'Исландский супер-густой йогурт, богатый белком, с акациевым медом',
        ingredients: ['Скир (исландский йогурт)', 'Мёд акациевый'],
        price: 320,
        rating: 4.8,
        ratingCount: 76,
        image: 'https://kuran.kg/breakfast/305.jpg',
        category: 'breakfast',
        tags: ['Кисломолочное', 'ЗОЖ', 'Белок'],
        calories: 180,
        cookingTime: 2,
        isVegetarian: true,
        isGlutenFree: true
    },
    {
        id: 306,
        name: 'Сдобная булочка Hot Cross Bun',
        nameEn: 'Hot Cross Bun',
        description: 'Традиционная английская булочка с изюмом и корицей, глазированная сахаром',
        ingredients: ['Мука', 'Изюм', 'Корица', 'Сахар', 'Яйцо', 'Сливочное масло'],
        price: 220,
        rating: 4.7,
        ratingCount: 54,
        image: 'https://kuran.kg/breakfast/306.jpg',
        category: 'breakfast',
        tags: ['Выпечка', 'Английский'],
        calories: 310,
        cookingTime: 5,
        isVegetarian: true
    },
    {
        id: 307,
        name: 'Апельсиновый мармелад домашний',
        nameEn: 'Homemade Orange Marmalade',
        description: 'Ароматный мармелад из севильских апельсинов с горьковатой цедрой',
        ingredients: ['Апельсины', 'Сахар', 'Пектин'],
        price: 130,
        rating: 4.9,
        ratingCount: 112,
        image: 'https://kuran.kg/breakfast/307.jpg',
        category: 'breakfast',
        tags: ['Джем', 'Домашнее'],
        calories: 80,
        cookingTime: 0,
        isVegetarian: true,
        isGlutenFree: true,
        isPopular: true
    },
    {
        id: 401,
        name: 'Сливочное масло',
        nameEn: 'Butter',
        description: 'Нежное сливочное масло 82.5% жирности',
        ingredients: ['Сливки', 'Соль'],
        price: 80,
        rating: 4.8,
        ratingCount: 345,
        image: 'https://kuran.kg/breakfast/401.jpg',
        category: 'breakfast',
        tags: ['Молочное'],
        calories: 120,
        cookingTime: 0,
        isVegetarian: true,
        isGlutenFree: true
    },
    {
        id: 402,
        name: 'Ассорти джемов (3 вида)',
        nameEn: 'Jam Assortment (3 kinds)',
        description: 'Малиновый, абрикосовый и клубничный джем ручной работы',
        ingredients: ['Малина', 'Абрикос', 'Клубника', 'Сахар', 'Пектин'],
        price: 150,
        rating: 4.9,
        ratingCount: 98,
        image: 'https://kuran.kg/breakfast/402.jpg',
        category: 'breakfast',
        tags: ['Джем', 'Домашнее'],
        calories: 180,
        cookingTime: 0,
        isVegetarian: true,
        isGlutenFree: true,
        isPopular: true
    },
    {
        id: 403,
        name: 'Зерновой тост',
        nameEn: 'Whole Grain Toast',
        description: 'Хрустящий тост из муки грубого помола с отрубями',
        ingredients: ['Мука грубого помола', 'Отруби', 'Дрожжи', 'Соль'],
        price: 70,
        rating: 4.7,
        ratingCount: 156,
        image: 'https://kuran.kg/breakfast/403.jpg',
        category: 'breakfast',
        tags: ['Хлеб', 'ЗОЖ'],
        calories: 110,
        cookingTime: 2,
        isVegetarian: true
    },
    {
        id: 404,
        name: 'Яйцо пашот на тосте',
        nameEn: 'Poached Egg on Toast',
        description: 'Нежное яйцо пашот на хрустящем тосте с голландским соусом (подается только по воскресеньям)',
        ingredients: ['Яйцо', 'Тост', 'Голландский соус', 'Уксус', 'Соль'],
        price: 180,
        rating: 4.9,
        ratingCount: 67,
        image: 'https://kuran.kg/breakfast/404.webp',
        category: 'breakfast',
        tags: ['Яйца', 'Воскресенье'],
        calories: 210,
        cookingTime: 8,
        isVegetarian: true
    }
]