import {
    Pizza, // Добавим для пиццы
    Egg,
    Fish,
    Beef,
    Coffee,
    Wine, Utensils, Leaf,
} from "lucide-react"

export interface MenuItem {
    id: number;
    name: string;
    nameEn: string;
    description: string;
    ingredients: string[];
    price: number;
    oldPrice?: number;
    rating: number;
    ratingCount: number;
    image: string;
    category: string;
    tags: string[];
    calories: number;
    cookingTime: number;
    isSpicy?: boolean;
    isVegetarian?: boolean;
    isGlutenFree?: boolean;
    isPopular?: boolean;
    isNew?: boolean;
}

// Категории меню (расширены)
export const categories = [
    { id: 'all', name: 'Все', icon: <Utensils className="w-5 h-5" /> },
    { id: 'starters', name: 'Закуски', icon: <Utensils className="w-5 h-5" /> },
    { id: 'salads', name: 'Салаты', icon: <Leaf className="w-5 h-5" /> },
    { id: 'soups', name: 'Супы', icon: <Utensils className="w-5 h-5" /> },
    { id: 'main', name: 'Основные блюда', icon: <Beef className="w-5 h-5" /> },
    { id: 'fish', name: 'Рыба & Морепродукты', icon: <Fish className="w-5 h-5" /> },
    { id: 'pasta', name: 'Паста & Риcотто', icon: <Utensils className="w-5 h-5" /> },
    { id: 'pizza', name: 'Пицца', icon: <Pizza className="w-5 h-5" /> },
    { id: 'desserts', name: 'Десерты', icon: <Utensils className="w-5 h-5" /> },
    { id: 'wine', name: 'Винная карта', icon: <Wine className="w-5 h-5" /> },
    { id: 'cocktails', name: 'Коктейли', icon: <Coffee className="w-5 h-5" /> },
    { id: 'non-alcoholic', name: 'Безалкогольные', icon: <Coffee className="w-5 h-5" /> },
    { id: 'breakfast', name: 'Завтраки', icon: <Egg className="w-5 h-5" /> }
];

// Данные меню (более 40 позиций)
export const menuItems: MenuItem[] = [
    // ============= ЗАКУСКИ (Starters) =============
    {
        id: 1,
        name: 'Устрицы с лимоном',
        nameEn: 'Oysters with lemon',
        description: 'Свежайшие устрицы, подаются с лимоном и соусом маринад',
        ingredients: ['Устрицы', 'Лимон', 'Соус маринад', 'Лед'],
        price: 1890,
        oldPrice: 2200,
        rating: 4.8,
        ratingCount: 124,
        image: 'https://images.unsplash.com/photo-1583425429970-7bb4f49e0d0e',
        category: 'starters',
        tags: ['Популярное', 'Новинка'],
        calories: 120,
        cookingTime: 15,
        isPopular: true,
        isNew: true
    },
    {
        id: 2,
        name: 'Фуа-гра с бриошью',
        nameEn: 'Foie gras with brioche',
        description: 'Нежная фуа-гра, обжаренная до золотистой корочки, подается с бриошью и ягодным конфитюром',
        ingredients: ['Фуа-гра', 'Бриошь', 'Ягодный конфитюр', 'Микс-салат'],
        price: 2200,
        rating: 4.9,
        ratingCount: 89,
        image: 'https://images.unsplash.com/photo-1608047601547-918c1b315bd3',
        category: 'starters',
        tags: ['Хит'],
        calories: 350,
        cookingTime: 20,
        isPopular: true
    },
    {
        id: 3,
        name: 'Тартар из говядины',
        nameEn: 'Beef tartare',
        description: 'Классический французский тартар из вырезки с каперсами и перепелиным яйцом',
        ingredients: ['Говяжья вырезка', 'Каперсы', 'Лук шалот', 'Перепелиное яйцо', 'Горчица'],
        price: 1650,
        rating: 4.7,
        ratingCount: 56,
        image: 'https://images.unsplash.com/photo-1666359859730-97a5cc6f9b1d',
        category: 'starters',
        tags: ['Хит'],
        calories: 280,
        cookingTime: 15
    },
    {
        id: 17,
        name: 'Буррата с прошутто',
        nameEn: 'Burrata with prosciutto',
        description: 'Нежная буррата, вяленая ветчина, рукола и бальзамический крем',
        ingredients: ['Буррата', 'Прошутто', 'Рукола', 'Бальзамик', 'Помидоры черри'],
        price: 1450,
        rating: 4.9,
        ratingCount: 42,
        image: 'https://images.unsplash.com/photo-1565951175155-158714f48c06',
        category: 'starters',
        tags: ['Популярное'],
        calories: 420,
        cookingTime: 10,
        isPopular: true
    },
    {
        id: 18,
        name: 'Гребешки с пармезаном',
        nameEn: 'Scallops with parmesan',
        description: 'Обжаренные гребешки в сливочном соусе с пармезаном и трюфельным маслом',
        ingredients: ['Гребешки', 'Сливки', 'Пармезан', 'Трюфельное масло'],
        price: 1850,
        rating: 4.8,
        ratingCount: 34,
        image: 'https://images.unsplash.com/photo-1614644147798-f8c0fc9da7f6',
        category: 'starters',
        tags: ['Новинка', 'Премиум'],
        calories: 310,
        cookingTime: 15,
        isNew: true
    },

    // ============= САЛАТЫ (Salads) =============
    {
        id: 4,
        name: 'Цезарь с креветками',
        nameEn: 'Caesar with shrimps',
        description: 'Классический салат Цезарь с тигровыми креветками и пармезаном',
        ingredients: ['Римский салат', 'Тигровые креветки', 'Пармезан', 'Соус Цезарь', 'Гренки'],
        price: 980,
        rating: 4.6,
        ratingCount: 203,
        image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9',
        category: 'salads',
        tags: ['Популярное'],
        calories: 320,
        cookingTime: 10,
        isPopular: true
    },
    {
        id: 5,
        name: 'Нисуаз с тунцом',
        nameEn: 'Niçoise with tuna',
        description: 'Провансальский салат с тунцом, перепелиными яйцами и оливками',
        ingredients: ['Тунец', 'Перепелиные яйца', 'Оливки', 'Помидоры черри', 'Фасоль'],
        price: 1150,
        rating: 4.7,
        ratingCount: 67,
        image: 'https://images.unsplash.com/photo-1626079916505-7e51b8a2e2cd',
        category: 'salads',
        tags: ['Новинка'],
        calories: 280,
        cookingTime: 12,
        isNew: true
    },
    {
        id: 19,
        name: 'Греческий салат',
        nameEn: 'Greek salad',
        description: 'Сочные овощи, фета, оливки и орегано',
        ingredients: ['Помидоры', 'Огурцы', 'Перец', 'Фета', 'Оливки', 'Орегано'],
        price: 650,
        rating: 4.5,
        ratingCount: 189,
        image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe',
        category: 'salads',
        tags: ['Вегетарианское'],
        calories: 210,
        cookingTime: 8,
        isVegetarian: true
    },
    {
        id: 20,
        name: 'Теплый салат с утиной грудкой',
        nameEn: 'Warm duck salad',
        description: 'Слайсы утиной грудки на подушке из микса салата с апельсиновой заправкой',
        ingredients: ['Утиная грудка', 'Микс-салат', 'Апельсин', 'Кедровые орехи', 'Мед'],
        price: 1250,
        rating: 4.8,
        ratingCount: 95,
        image: 'https://images.unsplash.com/photo-1534665482403-a909d0d97c67',
        category: 'salads',
        tags: ['Хит'],
        calories: 340,
        cookingTime: 15,
        isPopular: true
    },

    // ============= СУПЫ (Soups) =============
    {
        id: 21,
        name: 'Трюфельный суп',
        nameEn: 'Truffle soup',
        description: 'Ароматный суп из белых грибов с трюфельным маслом и сливками',
        ingredients: ['Белые грибы', 'Сливки', 'Трюфельное масло', 'Гренки'],
        price: 890,
        rating: 4.9,
        ratingCount: 67,
        image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a',
        category: 'soups',
        tags: ['Хит'],
        calories: 280,
        cookingTime: 15,
        isPopular: true
    },
    {
        id: 22,
        name: 'Французский луковый суп',
        nameEn: 'French onion soup',
        description: 'Традиционный луковый суп с сырной гренкой',
        ingredients: ['Лук', 'Говяжий бульон', 'Сыр Грюйер', 'Багет'],
        price: 690,
        rating: 4.7,
        ratingCount: 112,
        image: 'https://images.unsplash.com/photo-1547592166-23ac457cacf1',
        category: 'soups',
        tags: ['Классика'],
        calories: 310,
        cookingTime: 25
    },
    {
        id: 23,
        name: 'Том Ям с креветками',
        nameEn: 'Tom Yum with shrimps',
        description: 'Острый кисло-сладкий суп с морепродуктами и кокосовым молоком',
        ingredients: ['Креветки', 'Кокосовое молоко', 'Лемонграсс', 'Грибы', 'Кинза'],
        price: 790,
        rating: 4.8,
        ratingCount: 145,
        image: 'https://images.unsplash.com/photo-1607503878559-5a92d5d8d3e7',
        category: 'soups',
        tags: ['Острое', 'Популярное'],
        calories: 250,
        cookingTime: 15,
        isPopular: true
    },
    {
        id: 24,
        name: 'Борщ с пампушками',
        nameEn: 'Borscht with garlic buns',
        description: 'Классический красный борщ с говядиной, подается со сметаной и пампушками',
        ingredients: ['Свекла', 'Говядина', 'Капуста', 'Картофель', 'Пампушки'],
        price: 550,
        rating: 4.9,
        ratingCount: 201,
        image: 'https://images.unsplash.com/photo-1588953931558-61f3f800b10a',
        category: 'soups',
        tags: ['Хит', 'Домашняя кухня'],
        calories: 340,
        cookingTime: 20,
        isPopular: true
    },

    // ============= ОСНОВНЫЕ БЛЮДА (Main Courses) =============
    {
        id: 6,
        name: 'Рибай стейк',
        nameEn: 'Ribeye steak',
        description: 'Мраморная говядина, обжаренная на гриле с розмарином и чесночным маслом',
        ingredients: ['Мраморная говядина', 'Розмарин', 'Чесночное масло', 'Тимьян'],
        price: 3450,
        rating: 4.9,
        ratingCount: 156,
        image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e',
        category: 'main',
        tags: ['Хит', 'Популярное'],
        calories: 650,
        cookingTime: 25,
        isPopular: true
    },
    {
        id: 7,
        name: 'Утиная грудка',
        nameEn: 'Duck breast',
        description: 'Утиная грудка с апельсиновым соусом и запеченными овощами',
        ingredients: ['Утиная грудка', 'Апельсиновый соус', 'Овощи гриль', 'Тимьян'],
        price: 2150,
        rating: 4.8,
        ratingCount: 98,
        image: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369',
        category: 'main',
        tags: ['Хит'],
        calories: 480,
        cookingTime: 20
    },
    {
        id: 25,
        name: 'Ягненок с розмарином',
        nameEn: 'Lamb with rosemary',
        description: 'Нежные бараньи ребрышки с соусом из красного вина и овощами',
        ingredients: ['Баранина', 'Розмарин', 'Красное вино', 'Овощи гриль'],
        price: 2950,
        rating: 4.8,
        ratingCount: 76,
        image: 'https://images.unsplash.com/photo-1604917869287-07ef070d23f9',
        category: 'main',
        tags: ['Премиум'],
        calories: 580,
        cookingTime: 30,
        isNew: true
    },
    {
        id: 26,
        name: 'Веллингтон',
        nameEn: 'Beef Wellington',
        description: 'Филе говядины в слоеном тесте с грибным дюкселем',
        ingredients: ['Говяжья вырезка', 'Слоеное тесто', 'Грибы', 'Прошутто'],
        price: 3990,
        rating: 4.9,
        ratingCount: 45,
        image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143',
        category: 'main',
        tags: ['Подпись шефа'],
        calories: 720,
        cookingTime: 45,
        isPopular: true
    },

    // ============= РЫБА & МОРЕПРОДУКТЫ =============
    {
        id: 8,
        name: 'Лосось на гриле',
        nameEn: 'Grilled salmon',
        description: 'Филе лосося с овощами гриль и голландским соусом',
        ingredients: ['Лосось', 'Спаржа', 'Цукини', 'Голландский соус'],
        price: 2350,
        rating: 4.7,
        ratingCount: 112,
        image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288',
        category: 'fish',
        tags: ['Популярное'],
        calories: 520,
        cookingTime: 20,
        isPopular: true
    },
    {
        id: 27,
        name: 'Дорадо с лимоном',
        nameEn: 'Dorado with lemon',
        description: 'Целая дорадо, запеченная с травами и лимоном',
        ingredients: ['Дорадо', 'Лимон', 'Тимьян', 'Оливковое масло'],
        price: 1850,
        rating: 4.6,
        ratingCount: 88,
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2',
        category: 'fish',
        tags: ['Хит'],
        calories: 380,
        cookingTime: 25,
        isPopular: true
    },
    {
        id: 28,
        name: 'Паэлья с морепродуктами',
        nameEn: 'Seafood paella',
        description: 'Испанская паэлья с мидиями, креветками, кальмарами и цыпленком',
        ingredients: ['Мидии', 'Креветки', 'Кальмары', 'Рис', 'Шафран'],
        price: 2450,
        rating: 4.8,
        ratingCount: 67,
        image: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a',
        category: 'fish',
        tags: ['Новинка'],
        calories: 590,
        cookingTime: 35,
        isNew: true
    },

    // ============= ПАСТА & РИЗОТТО =============
    {
        id: 9,
        name: 'Паста с трюфелем',
        nameEn: 'Truffle pasta',
        description: 'Домашняя паста с трюфельным маслом и пармезаном',
        ingredients: ['Домашняя паста', 'Трюфельное масло', 'Пармезан', 'Сливки'],
        price: 1650,
        rating: 4.8,
        ratingCount: 87,
        image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141',
        category: 'pasta',
        tags: ['Хит'],
        calories: 580,
        cookingTime: 15,
        isPopular: true
    },
    {
        id: 29,
        name: 'Карбонара',
        nameEn: 'Carbonara',
        description: 'Классическая паста с гуанчиале, яйцом и пекорино романо',
        ingredients: ['Спагетти', 'Гуанчиале', 'Яйца', 'Пекорино', 'Перец'],
        price: 890,
        rating: 4.7,
        ratingCount: 156,
        image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3',
        category: 'pasta',
        tags: ['Популярное'],
        calories: 620,
        cookingTime: 15,
        isPopular: true
    },
    {
        id: 30,
        name: 'Ризотто с белыми грибами',
        nameEn: 'Mushroom risotto',
        description: 'Кремовое ризотто с лесными грибами и трюфельным маслом',
        ingredients: ['Рис Арборио', 'Белые грибы', 'Пармезан', 'Трюфельное масло'],
        price: 1190,
        rating: 4.8,
        ratingCount: 94,
        image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371',
        category: 'pasta',
        tags: ['Вегетарианское'],
        calories: 540,
        cookingTime: 20,
        isVegetarian: true
    },

    // ============= ПИЦЦА =============
    {
        id: 31,
        name: 'Маргарита',
        nameEn: 'Margherita',
        description: 'Томатный соус, моцарелла, базилик, оливковое масло',
        ingredients: ['Томатный соус', 'Моцарелла', 'Базилик', 'Оливковое масло'],
        price: 690,
        rating: 4.7,
        ratingCount: 234,
        image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca',
        category: 'pizza',
        tags: ['Классика'],
        calories: 780,
        cookingTime: 12,
        isVegetarian: true
    },
    {
        id: 32,
        name: 'Пепперони',
        nameEn: 'Pepperoni',
        description: 'Пикантная пепперони, моцарелла, томатный соус, орегано',
        ingredients: ['Пепперони', 'Моцарелла', 'Томатный соус', 'Орегано'],
        price: 890,
        rating: 4.9,
        ratingCount: 178,
        image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e',
        category: 'pizza',
        tags: ['Хит'],
        calories: 850,
        cookingTime: 15,
        isPopular: true
    },
    {
        id: 33,
        name: 'Четыре сыра',
        nameEn: 'Quattro Formaggi',
        description: 'Моцарелла, горгонзола, пармезан, фонтина',
        ingredients: ['Моцарелла', 'Горгонзола', 'Пармезан', 'Фонтина'],
        price: 990,
        rating: 4.8,
        ratingCount: 145,
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591',
        category: 'pizza',
        tags: ['Популярное'],
        calories: 820,
        cookingTime: 15,
        isVegetarian: true,
        isPopular: true
    },

    // ============= ДЕСЕРТЫ =============
    {
        id: 10,
        name: 'Крем-брюле',
        nameEn: 'Crème brûlée',
        description: 'Классический французский десерт с ванилью и карамельной корочкой',
        ingredients: ['Сливки', 'Ваниль', 'Желтки', 'Сахар', 'Ягоды'],
        price: 650,
        rating: 4.9,
        ratingCount: 178,
        image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc',
        category: 'desserts',
        tags: ['Хит', 'Популярное'],
        calories: 320,
        cookingTime: 10,
        isPopular: true
    },
    {
        id: 11,
        name: 'Шоколадный фондан',
        nameEn: 'Chocolate fondant',
        description: 'Горячий шоколадный десерт с жидкой сердцевиной и мороженым',
        ingredients: ['Шоколад', 'Сливочное масло', 'Мука', 'Мороженое'],
        price: 590,
        rating: 4.8,
        ratingCount: 145,
        image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c',
        category: 'desserts',
        tags: ['Популярное'],
        calories: 380,
        cookingTime: 15,
        isPopular: true
    },
    {
        id: 34,
        name: 'Тирамису',
        nameEn: 'Tiramisu',
        description: 'Итальянский десерт с маскарпоне, кофе и какао',
        ingredients: ['Маскарпоне', 'Савоярди', 'Кофе', 'Какао', 'Яйца'],
        price: 550,
        rating: 4.9,
        ratingCount: 167,
        image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9',
        category: 'desserts',
        tags: ['Хит'],
        calories: 350,
        cookingTime: 10,
        isPopular: true
    },
    {
        id: 35,
        name: 'Чизкейк Нью-Йорк',
        nameEn: 'New York cheesecake',
        description: 'Нежный сливочный чизкейк с ягодным соусом',
        ingredients: ['Сливочный сыр', 'Сливки', 'Печенье', 'Ягоды'],
        price: 590,
        rating: 4.7,
        ratingCount: 134,
        image: 'https://images.unsplash.com/photo-1533134242443-d4fd45e6d9b8',
        category: 'desserts',
        tags: ['Классика'],
        calories: 420,
        cookingTime: 10
    },

    // ============= ВИНА =============
    {
        id: 12,
        name: 'Шато Марго 2015',
        nameEn: 'Château Margaux 2015',
        description: 'Красное сухое вино, Бордо, Франция',
        ingredients: ['Каберне Совиньон', 'Мерло', 'Каберне Фран'],
        price: 18900,
        rating: 4.9,
        ratingCount: 34,
        image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32e6',
        category: 'wine',
        tags: ['Коллекционное'],
        calories: 620,
        cookingTime: 0,
        isPopular: false
    },
    {
        id: 13,
        name: 'Дом Периньон 2012',
        nameEn: 'Dom Pérignon 2012',
        description: 'Шампанское, Франция',
        ingredients: ['Пино Нуар', 'Шардоне'],
        price: 25900,
        rating: 5.0,
        ratingCount: 28,
        image: 'https://images.unsplash.com/photo-1594712941268-3e43e6308f7d',
        category: 'wine',
        tags: ['Премиум'],
        calories: 580,
        cookingTime: 0
    },
    {
        id: 36,
        name: 'Сансерр 2022',
        nameEn: 'Sancerre 2022',
        description: 'Белое сухое вино из совиньон блан, Луара',
        ingredients: ['Совиньон Блан'],
        price: 8900,
        rating: 4.7,
        ratingCount: 45,
        image: 'https://images.unsplash.com/photo-1578911373732-2d7e198b2c13',
        category: 'wine',
        tags: ['Рекомендуем'],
        calories: 590,
        cookingTime: 0
    },

    // ============= КОКТЕЙЛИ =============
    {
        id: 14,
        name: 'Мохито',
        nameEn: 'Mojito',
        description: 'Освежающий коктейль с мятой и лаймом',
        ingredients: ['Белый ром', 'Мята', 'Лайм', 'Содовая', 'Тростниковый сахар'],
        price: 690,
        rating: 4.7,
        ratingCount: 234,
        image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a',
        category: 'cocktails',
        tags: ['Популярное'],
        calories: 180,
        cookingTime: 5,
        isPopular: true
    },
    {
        id: 15,
        name: 'Маргарита',
        nameEn: 'Margarita',
        description: 'Классическая текила с апельсиновым ликером',
        ingredients: ['Текила', 'Трипл-сек', 'Лайм', 'Соль'],
        price: 650,
        rating: 4.6,
        ratingCount: 167,
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87',
        category: 'cocktails',
        tags: ['Хит'],
        calories: 190,
        cookingTime: 5
    },
    {
        id: 37,
        name: 'Эспрессо Мартини',
        nameEn: 'Espresso Martini',
        description: 'Кофейный коктейль с водкой и ликером',
        ingredients: ['Водка', 'Кофе эспрессо', 'Кофейный ликер', 'Сахарный сироп'],
        price: 750,
        rating: 4.9,
        ratingCount: 98,
        image: 'https://images.unsplash.com/photo-1594053050894-f9a4b0a3a14b',
        category: 'cocktails',
        tags: ['Новинка'],
        calories: 210,
        cookingTime: 5,
        isNew: true
    },
    {
        id: 38,
        name: 'Апероль Шприц',
        nameEn: 'Aperol Spritz',
        description: 'Легкий итальянский аперитив',
        ingredients: ['Апероль', 'Просекко', 'Содовая', 'Апельсин'],
        price: 690,
        rating: 4.8,
        ratingCount: 156,
        image: 'https://images.unsplash.com/photo-1605095382254-184ef648afd4',
        category: 'cocktails',
        tags: ['Популярное'],
        calories: 170,
        cookingTime: 3,
        isPopular: true
    },

    // ============= БЕЗАЛКОГОЛЬНЫЕ =============
    {
        id: 16,
        name: 'Свежевыжатый апельсиновый сок',
        nameEn: 'Fresh orange juice',
        description: 'Натуральный апельсиновый сок',
        ingredients: ['Апельсины'],
        price: 390,
        rating: 4.8,
        ratingCount: 98,
        image: 'https://images.unsplash.com/photo-1613478226514-7f3e4e6d4c4f',
        category: 'non-alcoholic',
        tags: ['Натуральное'],
        calories: 120,
        cookingTime: 3,
        isVegetarian: true,
        isGlutenFree: true
    },
    {
        id: 39,
        name: 'Лимонад "Домашний"',
        nameEn: 'Homemade lemonade',
        description: 'Освежающий лимонад с мятой и имбирем',
        ingredients: ['Лимон', 'Мята', 'Имбирь', 'Сахар', 'Газированная вода'],
        price: 450,
        rating: 4.9,
        ratingCount: 187,
        image: 'https://images.unsplash.com/photo-1529676686924-ca5b1b8e3e0b',
        category: 'non-alcoholic',
        tags: ['Популярное'],
        calories: 110,
        cookingTime: 5,
        isVegetarian: true,
        isPopular: true
    },
    {
        id: 40,
        name: 'Смузи "Тропический"',
        nameEn: 'Tropical smoothie',
        description: 'Смузи из манго, ананаса и банана',
        ingredients: ['Манго', 'Ананас', 'Банан', 'Йогурт'],
        price: 520,
        rating: 4.7,
        ratingCount: 76,
        image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859',
        category: 'non-alcoholic',
        tags: ['Новинка'],
        calories: 210,
        cookingTime: 5,
        isVegetarian: true,
        isGlutenFree: true,
        isNew: true
    },
    {
        id: 41,
        name: 'Матча Латте',
        nameEn: 'Matcha Latte',
        description: 'Японский чай матча с молоком',
        ingredients: ['Матча', 'Молоко', 'Сироп (по желанию)'],
        price: 490,
        rating: 4.8,
        ratingCount: 54,
        image: 'https://images.unsplash.com/photo-1534777273951-d5c174085af5',
        category: 'non-alcoholic',
        tags: ['Популярное'],
        calories: 150,
        cookingTime: 5,
        isVegetarian: true,
        isPopular: true
    },

    // ============= ЗАВТРАКИ (Breakfast) =============
    {
        id: 42,
        name: 'Английский завтрак',
        nameEn: 'Full English breakfast',
        description: 'Яйца пашот, бекон, сосиски, бобы, томаты, грибы, тост',
        ingredients: ['Яйца', 'Бекон', 'Сосиски', 'Бобы', 'Томаты', 'Грибы', 'Тост'],
        price: 890,
        rating: 4.8,
        ratingCount: 112,
        image: 'https://images.unsplash.com/photo-1536312524968-db3c1cde9035',
        category: 'breakfast',
        tags: ['Хит'],
        calories: 680,
        cookingTime: 20,
        isPopular: true
    },
    {
        id: 43,
        name: 'Овсяная каша с ягодами',
        nameEn: 'Oatmeal with berries',
        description: 'Нежная овсяная каша на кокосовом молоке со свежими ягодами',
        ingredients: ['Овсяные хлопья', 'Кокосовое молоко', 'Ягоды', 'Мед', 'Миндаль'],
        price: 490,
        rating: 4.7,
        ratingCount: 67,
        image: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf',
        category: 'breakfast',
        tags: ['Полезное'],
        calories: 320,
        cookingTime: 10,
        isVegetarian: true,
        isGlutenFree: true
    },
    {
        id: 44,
        name: 'Сырники с малиновым вареньем',
        nameEn: 'Syrniki with raspberry jam',
        description: 'Творожные сырники, подаются со сметаной и малиновым вареньем',
        ingredients: ['Творог', 'Мука', 'Яйца', 'Сметана', 'Малиновое варенье'],
        price: 550,
        rating: 4.9,
        ratingCount: 145,
        image: 'https://images.unsplash.com/photo-1582736031703-47b698fa190c',
        category: 'breakfast',
        tags: ['Популярное'],
        calories: 380,
        cookingTime: 15,
        isPopular: true
    },
    {
        id: 45,
        name: 'Смузи Боул "Асаи"',
        nameEn: 'Acai Smoothie Bowl',
        description: 'Густой смузи из асаи с гранолой и свежими фруктами',
        ingredients: ['Асаи', 'Банан', 'Гранола', 'Манго', 'Кокосовая стружка'],
        price: 650,
        rating: 4.8,
        ratingCount: 43,
        image: 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38',
        category: 'breakfast',
        tags: ['Новинка', 'ЗОЖ'],
        calories: 290,
        cookingTime: 10,
        isVegetarian: true,
        isGlutenFree: true,
        isNew: true
    }
];
